import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "../../redux/Provider";
import { UIProvider } from "../../contexts/useUIContext";
const segoe = Inter({ variable: "--font-inter", subsets: ["latin"] });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${segoe.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UIProvider>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </UIProvider>
      </body>
    </html>
  );
}
